### ISSUE TITLE
Systemd running dind and stats fails

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#10690]
Reproducible on a systemd machine:

```
TESTFLAGS='-v -run TestGetContainerStats' make test-integration-cli
```

Probably something with systemd cgroups

**Comment by LK4D4** [comment]
Probably bug in libcontainer about subcgroups detection. Systemd has `cpu,cpuacct` cgroup, but in container there are separate `cpu` and `cpuacct` cgroups.

**Comment by vbatts** [comment]
fixit fixit fixit
:pray:

**Comment by lsm5** [comment]
btw, I see this on RHEL/CentOS 7 as well as ubuntu 14.04 for `make test-integration-cli`

    [PASSED]: version - verify that it works and that the output is properly formatted
    FAIL
    coverage: 71.0% of statements
    exit status 1
    FAIL    github.com/docker/docker/integration-cli    1319.723s
    ++++ cat /go/src/github.com/docker/docker/bundles/1.5.0-dev/test-integration-cli/daemon30809327/docker.pid
    +++ kill 27690
    /go/src/github.com/docker/docker/hack/make/.integration-daemon-stop: line 6: wait: pid 27690 is not a child of this shell
    warning: PID 27690 from /go/src/github.com/docker/docker/bundles/1.5.0-dev/test-integration-cli/daemon30809327/docker.pid had a nonzero exit code
    ++++ cat /go/src/github.com/docker/docker/bundles/1.5.0-dev/test-integration-cli/daemon32588737/docker.pid
    +++ kill 22034
    /go/src/github.com/docker/docker/hack/make/.integration-daemon-stop: line 6: wait: pid 22034 is not a child of this shell
    warning: PID 22034 from /go/src/github.com/docker/docker/bundles/1.5.0-dev/test-integration-cli/daemon32588737/docker.pid had a nonzero exit code
    ++++ cat /go/src/github.com/docker/docker/bundles/1.5.0-dev/test-integration-cli/daemon49502928/docker.pid
    +++ kill 22263
    /go/src/github.com/docker/docker/hack/make/.integration-daemon-stop: line 6: wait: pid 22263 is not a child of this shell
    warning: PID 22263 from /go/src/github.com/docker/docker/bundles/1.5.0-dev/test-integration-cli/daemon49502928/docker.pid had a nonzero exit code
    ++++ cat /go/src/github.com/docker/docker/bundles/1.5.0-dev/test-integration-cli/docker.pid
    +++ kill 685
    make: *** [test-integration-cli] Error 1

**Comment by vbatts** [comment]
@lsm5 can you run just `TESTFLAGS='-v -run TestGetContainerStats' make test-integration-cli` ?

**Comment by lsm5** [comment]
`TESTFLAGS='-v -run TestGetContainerStats' make test-integration-cli`

-works on ubuntu 14.04

-fails on CentOS 6 (not sure why it complains `no such file or dir`):


    Sending build context to Docker daemon 
    time="2015-02-18T03:02:57Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.18/build?dockerfile=Dockerfile&rm=1&t=busybox: dial unix /var/run/docker.sock: no such file or directory" 
    +++ tar -cC /go/src/github.com/docker/docker/bundles/1.5.0-dev/test-integration-cli/emptyfs .
    +++ docker load
    time="2015-02-18T03:02:57Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.18/images/load: dial unix /var/run/docker.sock: no such file or directory" 
    + go test -v -run TestGetContainerStats -test.timeout=30m github.com/docker/docker/integration-cli
    === RUN TestGetContainerStats
    time="2015-02-18T03:03:04Z" level="fatal" msg="Get http:///var/run/docker.sock/v1.18/containers/json?all=1: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?" 

    --- FAIL: TestGetContainerStats (0.12s)
    	docker_api_containers_test.go:302: Error on container creation: exit status 1, output: "time=\"2015-02-18T03:03:03Z\" level=\"fatal\" msg=\"Post http:///var/run/docker.sock/v1.18/containers/create?name=statscontainer: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?\" \n"
    FAIL
    coverage: 4.5% of statements
    exit status 1
    FAIL	github.com/docker/docker/integration-cli	0.137s
    ++++ cat /go/src/github.com/docker/docker/bundles/1.5.0-dev/test-integration-cli/docker.pid
    +++ kill 644
    /go/src/github.com/docker/docker/hack/make/.integration-daemon-stop: line 5: kill: (644) - No such process
    make: *** [test-integration-cli] Error 1

-fails on CentOS 7:

    + go test -v -run TestGetContainerStats -test.timeout=30m github.com/docker/docker/integration-cli
    === RUN TestGetContainerStats
    --- FAIL: TestGetContainerStats (4.39s)
    	docker_api_containers_test.go:334: EOF
    FAIL
    coverage: 11.2% of statements
    exit status 1
    FAIL	github.com/docker/docker/integration-cli	4.398s
    ++++ cat /go/src/github.com/docker/docker/bundles/1.5.0-dev/test-integration-cli/docker.pid
    +++ kill 703
    make: *** [test-integration-cli] Error 1

**Comment by LK4D4** [comment]
Looks like panic.

**Comment by vbatts** [comment]
@jfrazelle i'm ready to propose a PR like 

```diff
diff --git a/integration-cli/docker_api_containers_test.go b/integration-cli/docker_api_containers_test.go
index ad995b7..528298a 100644
--- a/integration-cli/docker_api_containers_test.go
+++ b/integration-cli/docker_api_containers_test.go
@@ -331,6 +331,9 @@ func TestGetContainerStats(t *testing.T) {
                var s *stats.Stats
                // decode only one object from the stream
                if err := dec.Decode(&s); err != nil {
+                       if err == io.EOF {
+                               t.Skip("EOF Received, must be DinD on systemd ... https://github.com/docker/docker/issues/10690")
+                       }
                        t.Fatal(err)
                }
        }
```


Unless we can determine why being in systemd cgroup hierarchy is jamming up the stats API ...

**Comment by vbatts** [comment]
@crosbymichael ^^

**Comment by vbatts** [comment]
here is the daemon log of this failure

```
time="2015-02-19T15:41:17Z" level="info" msg="-job create(statscontainer) = OK (0)" 
time="2015-02-19T15:41:17Z" level="debug" msg="Calling POST /containers/{name:.*}/start" 
time="2015-02-19T15:41:17Z" level="info" msg="POST /v1.18/containers/7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b/start" 
time="2015-02-19T15:41:17Z" level="info" msg="+job start(7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b)" 
time="2015-02-19T15:41:17Z" level="info" msg="+job allocate_interface(7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b)" 
time="2015-02-19T15:41:17Z" level="info" msg="-job allocate_interface(7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b) = OK (0)" 
time="2015-02-19T15:41:17Z" level="info" msg="+job log(start, 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b, busybox:latest)" 
time="2015-02-19T15:41:17Z" level="info" msg="-job log(start, 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b, busybox:latest) = OK (0)" 
time="2015-02-19T15:41:17Z" level="info" msg="-job start(7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b) = OK (0)" 
time="2015-02-19T15:41:17Z" level="debug" msg="Calling GET /containers/{name:.*}/stats" 
time="2015-02-19T15:41:17Z" level="info" msg="GET /containers/statscontainer/stats" 
time="2015-02-19T15:41:17Z" level="info" msg="+job container_stats(statscontainer)" 
time="2015-02-19T15:41:17Z" level="error" msg="collecting stats for 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b: open /cgroup/cpuacct/system.slice/docker-24fd188be4a1bfaa4c2ef60afb5babea1300b5be9cd0ca0684c9a8a480e4a8d3.scope/docker/7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b/cpuacct.stat: no such file or directory" 
time="2015-02-19T15:41:18Z" level="error" msg="collecting stats for 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b: open /cgroup/cpuacct/system.slice/docker-24fd188be4a1bfaa4c2ef60afb5babea1300b5be9cd0ca0684c9a8a480e4a8d3.scope/docker/7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b/cpuacct.stat: no such file or directory" 
time="2015-02-19T15:41:19Z" level="error" msg="collecting stats for 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b: open /cgroup/cpuacct/system.slice/docker-24fd188be4a1bfaa4c2ef60afb5babea1300b5be9cd0ca0684c9a8a480e4a8d3.scope/docker/7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b/cpuacct.stat: no such file or directory" 
time="2015-02-19T15:41:20Z" level="error" msg="collecting stats for 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b: open /cgroup/cpuacct/system.slice/docker-24fd188be4a1bfaa4c2ef60afb5babea1300b5be9cd0ca0684c9a8a480e4a8d3.scope/docker/7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b/cpuacct.stat: no such file or directory" 
time="2015-02-19T15:41:21Z" level="debug" msg="Calling DELETE /containers/{name:.*}" 
time="2015-02-19T15:41:21Z" level="info" msg="DELETE /v1.18/containers/statscontainer?force=1" 
time="2015-02-19T15:41:21Z" level="info" msg="+job rm(statscontainer)" 
time="2015-02-19T15:41:21Z" level="debug" msg="Sending 9 to 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b" 
time="2015-02-19T15:41:21Z" level="info" msg="-job container_stats(statscontainer) = OK (0)" 
time="2015-02-19T15:41:21Z" level="info" msg="+job log(die, 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b, busybox:latest)" 
time="2015-02-19T15:41:21Z" level="info" msg="-job log(die, 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b, busybox:latest) = OK (0)" 
time="2015-02-19T15:41:21Z" level="info" msg="+job release_interface(7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b)" 
time="2015-02-19T15:41:21Z" level="info" msg="-job release_interface(7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b) = OK (0)" 
time="2015-02-19T15:41:21Z" level="info" msg="+job log(destroy, 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b, busybox:latest)" 
time="2015-02-19T15:41:21Z" level="info" msg="-job log(destroy, 7d3c14eccc03c013c8a68b630246b666a26d59e473df9118e700015235d9aa1b, busybox:latest) = OK (0)" 
time="2015-02-19T15:41:21Z" level="info" msg="-job rm(statscontainer) = OK (0)" 
```
